# Generated by Django 2.1.5 on 2019-01-06 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=120)),
                ('Time', models.DateTimeField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Surname', models.CharField(max_length=120)),
                ('Company', models.CharField(blank=True, max_length=120, null=True)),
                ('Job_Title', models.CharField(blank=True, max_length=120, null=True)),
                ('Auth_Token', models.CharField(blank=True, max_length=120, null=True)),
                ('Device_ID', models.CharField(blank=True, max_length=120, null=True)),
                ('State', models.CharField(blank=True, max_length=120, null=True)),
                ('Culture_Info', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Description', models.DateTimeField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserSubscription'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='UserA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserA', to='users.User'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='UserB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserB', to='users.User'),
        ),
    ]
