# Generated by Django 2.1.5 on 2019-01-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='Description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
